@jwt = eyJhbGciOiJIUzI1NiJ9.eyJ1c2VyX2lkIjoxLCJleHAiOjE2Njc5NDQ0MzR9.sZXH44zD0l5PfQSP_Ti_Sl33AMNtCAB8-cEYc4FLzus

### show all users
get http://localhost:3000/users.json

### show particular user
get http://localhost:3000/users/2.json

### create new user
POST http://localhost:3000/users
Content-Type: application/json

{
  "name": "Craig",
  "height": 80,
  "image_url": "test.jpg",
  "password": "password",
  "email": "craig@test.com"
}

### update a user
PATCH http://localhost:3000/users/4.json
Authorization: Bearer {{jwt}}
Content-Type: application/json

{
  "weight": 200
}

### delete a user 
DELETE http://localhost:3000/users/2.json
Content-Type: application/json

### show all exercises
get http://localhost:3000/exercises.json


### show a particular exercise
get http://localhost:3000/exercises/2.json

### show all workouts
get http://localhost:3000/workouts.json

### show a particular workout
get http://localhost:3000/workouts/1.json

### create a workout 
POST http://localhost:3000/workouts
Authorization: Bearer {{jwt}}
Content-Type: application/json

{
  "title": "Test Workout",
  "user_id": 4
}

### update a workout
PATCH http://localhost:3000/workouts/2.json
Authorization: Bearer {{jwt}}
Content-Type: application/json

{
"title": "New name",
"user_id": 1
}

### delete a workout
DELETE http://localhost:3000/workouts/1.json
Content-Type: application/json


### Sessions create (login)
POST http://localhost:3000/sessions.json
Content-Type: application/json

{
  "email": "marcus@test.com",
  "password": "password"
}

### create workout detail
POST http://localhost:3000/workout_details.json
Content-Type: application/json
Authorization: Bearer {{jwt}}

{
  "workout_id": 1,
  "exercise_id": 3,
  "reps": 15,
  "weight": 100,
  "sets": 3
}
